export const FETCH_CITY_FORCAST_SUCCESS = 'FETCH_CITY_FORCAST_SUCCESS';
export const FETCH_CITY_FORCAST_FAILURE = 'FETCH_CITY_FORCAST_FAILURE';
export const RESET_FORCAST = 'RESET_FORCAST';

export const FETCH_CURRENT_WEATHER_FOR_CITY_SUCCESS = 'FETCH_CURRENT_WEATHER_FOR_CITY_SUCCESS';
export const FETCH_CURRENT_WEATHER_FOR_CITY_FAILURE = 'FETCH_CURRENT_WEATHER_FOR_CITY_FAILURE';

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export const RESET_CURRENT_CITY = 'RESET_CURRENT_CITY';

export const FORCAST_URL = 'https://api.openweathermap.org/data/2.5/forecast';
export const WEATHER_DATA_URL = 'https://api.openweathermap.org/data/2.5/weather';
