export const FETCH_CURRENT_CITY_FORECAST_SUCCESS = 'FETCH_CURRENT_CITY_FORECAST_SUCCESS';
export const FETCH_CURRENT_CITY_FORECAST_FAILURE = 'FETCH_CURRENT_CITY_FORECAST_FAILURE';

export const FETCH_CURRENT_WEATHER_FOR_CITY_SUCCESS = 'FETCH_CURRENT_WEATHER_FOR_CITY_SUCCESS';
export const FETCH_CURRENT_WEATHER_FOR_CITY_FAILURE = 'FETCH_CURRENT_WEATHER_FOR_CITY_FAILURE';

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export const RESET_CURRENT_CITY = 'RESET_CURRENT_CITY';
